version: "2"

services:
  app:
    build:
      context: ../../
      dockerfile: infrastructure/prod/Dockerfile.app
    environment:
      - API_URL=http://server:3002
    restart: always
  server:
    build:
      context: ../../
      dockerfile: infrastructure/prod/Dockerfile.server
    env_file: ./server.env
    restart: always
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    restart: always
