version: "2"

services:
  postgresql:
    image: postgres:11.5
    ports:
      - 5432:5432
    volumes:
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
      - pg:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_MULTIPLE_DATABASES=dev,test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=

volumes:
  pg: